default:
  port: 4567
  supported_extensions:
    images: [".jpg", ".jpeg", ".png", ".gif", ".bmp", ".webp", ".svg"]
    audio: [".mp3", ".wav", ".ogg", ".m4a", ".flac"]
    video: [".mp4", ".avi", ".mkv", ".mov", ".webm"]