default:
  host: "localhost"
  port: 4567
  base_sound_level: -23.0
  supported_extensions:
    images: [".jpg", ".jpeg", ".png", ".gif", ".bmp", ".webp", ".svg", ".avif"]
    audio: [".mp3", ".wav", ".ogg", ".m4a", ".flac"]
    video: [".mp4", ".avi", ".mkv", ".mov", ".webm"]
  theme: "default"